import type { ServicePageData } from "@/components/shared/ServicePage";

export const RESEARCH_DATA: ServicePageData = {
  slug: "research",
  parentHref: "/layanan",
  parentLabel: "← Layanan",
  category: "Research",
  accentColor: "#266c87",
  heroGrad: "radial-gradient(ellipse 80% 60% at 20% 40%, rgba(38,108,135,0.25) 0%, transparent 60%)",
  heroIcon: "○",
  heroTitle: "Riset yang menggerakkan",
  heroTitleAccent: "perubahan nyata.",
  heroDesc: "Manara menyediakan layanan riset kebijakan berbasis bukti — dari identifikasi masalah hingga rekomendasi yang actionable untuk pengambil keputusan.",
  overviewTitle: "Riset bukan sekadar laporan. Ini fondasi perubahan.",
  overviewDesc: [
    "Manara Research adalah divisi kajian kebijakan yang bekerja di persimpangan antara akademik dan praktis. Kami tidak hanya mengumpulkan data — kami menginterpretasikannya dalam konteks yang relevan bagi pemangku kepentingan.",
    "Setiap proyek riset kami dirancang untuk dapat ditindaklanjuti: dari policy brief yang dapat dibaca dalam 10 menit hingga laporan komprehensif yang menjadi referensi jangka panjang.",
  ],
  overviewStats: [
    { value: "Berbasis", label: "Bukti empiris dan data primer" },
    { value: "Lokal", label: "Konteks Indonesia & Jawa Timur" },
    { value: "Akses", label: "Publikasi terbuka untuk publik" },
    { value: "Kolaboratif", label: "Lintas disiplin dan sektor" },
  ],
  features: [
    { icon: "◎", title: "Policy Research", desc: "Kajian mendalam terhadap isu kebijakan publik — pendidikan, lingkungan, ekonomi, dan sosial." },
    { icon: "◇", title: "Data Analysis", desc: "Pengolahan dan visualisasi data kuantitatif dan kualitatif yang mudah dipahami." },
    { icon: "○", title: "Literature Review", desc: "Tinjauan literatur sistematis sebagai fondasi akademik proyek riset." },
    { icon: "✦", title: "Field Research", desc: "Pengumpulan data lapangan melalui wawancara, survei, dan observasi." },
    { icon: "△", title: "Comparative Study", desc: "Studi komparatif antar daerah atau negara sebagai referensi kebijakan." },
    { icon: "□", title: "Impact Evaluation", desc: "Evaluasi dampak program dan kebijakan yang sudah atau sedang berjalan." },
  ],
  processTitle: "Dari pertanyaan ke rekomendasi.",
  processDesc: "Proses riset Manara dirancang untuk efisien, transparan, dan dapat dipercaya.",
  steps: [
    { num: "01", title: "Scoping & Problem Framing", desc: "Mendefinisikan pertanyaan riset, ruang lingkup, metodologi, dan target output bersama klien.", duration: "1–2 minggu" },
    { num: "02", title: "Data Collection", desc: "Pengumpulan data primer (wawancara, survei, FGD) dan sekunder (literatur, dokumen kebijakan).", duration: "2–4 minggu" },
    { num: "03", title: "Analysis & Synthesis", desc: "Analisis mendalam, interpretasi temuan, dan identifikasi pola serta anomali.", duration: "2–3 minggu" },
    { num: "04", title: "Drafting & Review", desc: "Penulisan laporan, review internal, dan iterasi berdasarkan masukan klien.", duration: "1–2 minggu" },
    { num: "05", title: "Final Delivery & Dissemination", desc: "Penyerahan laporan final, presentasi temuan, dan dukungan diseminasi publik.", duration: "1 minggu" },
  ],
  deliverables: [
    { icon: "◇", title: "Laporan Riset", desc: "Dokumen komprehensif dengan temuan, analisis, dan rekomendasi." },
    { icon: "○", title: "Policy Brief", desc: "Ringkasan 4–8 halaman untuk pengambil keputusan." },
    { icon: "✦", title: "Executive Summary", desc: "Ringkasan eksekutif 1–2 halaman untuk presentasi." },
    { icon: "△", title: "Dataset", desc: "Data mentah dan data olahan yang dapat digunakan ulang." },
    { icon: "□", title: "Presentasi", desc: "Slide deck untuk presentasi kepada pemangku kepentingan." },
    { icon: "◎", title: "Infografis", desc: "Visualisasi temuan kunci untuk konsumsi publik." },
  ],
  clients: [
    { icon: "🏛️", label: "Pemerintah Daerah" },
    { icon: "🌱", label: "NGO & CSO" },
    { icon: "🎓", label: "Akademisi & Peneliti" },
    { icon: "🏢", label: "Organisasi Internasional" },
    { icon: "📊", label: "Lembaga Think Tank" },
    { icon: "🤝", label: "Donor & Filantropi" },
  ],
  whyTitle: "Riset yang berpihak pada publik.",
  whyPoints: [
    { title: "Independent & Objektif", desc: "Tidak berafiliasi dengan kepentingan politik manapun. Temuan kami berbicara atas nama data." },
    { title: "Konteks Lokal yang Kuat", desc: "Pemahaman mendalam tentang dinamika sosial, budaya, dan politik Indonesia — khususnya Jawa Timur." },
    { title: "Akademik Sekaligus Praktis", desc: "Rigor akademik tanpa kehilangan relevansi praktis. Laporan kami bisa dibaca dan ditindaklanjuti." },
    { title: "Open Access", desc: "Sebagian besar temuan kami dipublikasikan secara terbuka untuk memperluas dampak." },
  ],
  faqs: [
    { q: "Berapa lama satu proyek riset biasanya berlangsung?", a: "Tergantung skala, rata-rata 6–12 minggu untuk proyek standar. Proyek cepat (rapid assessment) bisa selesai dalam 3–4 minggu." },
    { q: "Apakah Manara bisa mengerjakan riset di luar Jawa Timur?", a: "Ya. Kami memiliki jaringan peneliti lapangan di berbagai provinsi. Proyek nasional dapat dikerjakan dengan mitra lokal." },
    { q: "Bagaimana dengan kerahasiaan data klien?", a: "Semua data klien diperlakukan sebagai informasi konfidensial. Kami menandatangani NDA sebelum proyek dimulai." },
    { q: "Apakah bisa request topik spesifik?", a: "Tentu. Kami melayani commission research berdasarkan kebutuhan klien. Hubungi kami untuk diskusi awal." },
    { q: "Apakah ada biaya konsultasi awal?", a: "Tidak. Konsultasi awal untuk mendiskusikan kebutuhan dan scope proyek dilakukan secara gratis." },
  ],
  ctaTitle: "Siap memulai proyek riset bersama Manara?",
  ctaDesc: "Ceritakan kebutuhan risetmu. Kami akan merespons dalam 1×24 jam kerja.",
};

export const POLICY_BRIEF_DATA: ServicePageData = {
  slug: "policy-brief",
  parentHref: "/layanan",
  parentLabel: "← Layanan",
  category: "Policy Brief",
  accentColor: "#3F6F6A",
  heroGrad: "radial-gradient(ellipse 80% 60% at 80% 30%, rgba(63,111,106,0.2) 0%, transparent 60%)",
  heroIcon: "◇",
  heroTitle: "Kebijakan yang berbicara",
  heroTitleAccent: "dengan data.",
  heroDesc: "Policy brief Manara dirancang untuk menjembatani riset akademis dengan pengambil keputusan — singkat, tajam, dan dapat ditindaklanjuti.",
  overviewTitle: "Dari temuan riset menjadi rekomendasi yang dibaca.",
  overviewDesc: [
    "Policy brief yang baik bukan sekadar ringkasan laporan. Ini adalah instrumen advokasi yang harus bisa dibaca dalam 10 menit dan menghasilkan tindakan konkret dari pembacanya.",
    "Manara mengembangkan policy brief dengan standar internasional — dari problem framing yang tajam, evidence synthesis yang kuat, hingga rekomendasi yang spesifik dan dapat diimplementasikan.",
  ],
  overviewStats: [
    { value: "4–8", label: "Halaman, cukup untuk satu pertemuan" },
    { value: "10", label: "Menit untuk membaca seluruhnya" },
    { value: "Jelas", label: "Rekomendasi yang spesifik & terukur" },
    { value: "Siap", label: "Untuk presentasi ke stakeholder" },
  ],
  features: [
    { icon: "◎", title: "Executive Policy Brief", desc: "Dokumen 4–8 halaman untuk pejabat, eksekutif, dan pengambil keputusan tingkat tinggi." },
    { icon: "◇", title: "Legislative Brief", desc: "Brief khusus untuk anggota legislatif — fokus pada implikasi hukum dan regulasi." },
    { icon: "○", title: "Advocacy Brief", desc: "Dirancang untuk mendukung kampanye advokasi NGO dan kelompok masyarakat sipil." },
    { icon: "✦", title: "Technical Brief", desc: "Brief teknis untuk audiens yang lebih spesifik dengan pemahaman mendalam terhadap isu." },
    { icon: "△", title: "Rapid Brief", desc: "Produksi cepat untuk isu yang membutuhkan respons segera terhadap perkembangan kebijakan." },
  ],
  processTitle: "Dari isu ke dokumen yang menggerakkan.",
  processDesc: "Setiap policy brief kami melalui proses yang ketat namun efisien.",
  steps: [
    { num: "01", title: "Issue Identification", desc: "Mengidentifikasi dan memframing isu kebijakan yang akan diangkat, termasuk konteks dan urgensi.", duration: "2–3 hari" },
    { num: "02", title: "Evidence Review", desc: "Tinjauan cepat terhadap bukti yang relevan — data, studi, dan kebijakan yang sudah ada.", duration: "3–5 hari" },
    { num: "03", title: "Drafting", desc: "Penulisan brief dengan struktur standar: latar, masalah, temuan, dan rekomendasi.", duration: "3–5 hari" },
    { num: "04", title: "Review & Finalization", desc: "Review bersama klien, revisi, dan finalisasi desain untuk publikasi.", duration: "2–3 hari" },
  ],
  deliverables: [
    { icon: "◇", title: "Policy Brief (PDF)", desc: "Dokumen final terformat siap cetak dan distribusi digital." },
    { icon: "○", title: "Versi Ringkas (1 halaman)", desc: "One-pager untuk distribusi cepat dan media sosial." },
    { icon: "✦", title: "Presentasi Slide", desc: "Deck untuk mempresentasikan brief ke stakeholder." },
    { icon: "△", title: "Infografis Kunci", desc: "Visualisasi temuan dan rekomendasi utama." },
  ],
  clients: [
    { icon: "🏛️", label: "Kementerian & Pemda" },
    { icon: "🌱", label: "NGO & Advocacy Groups" },
    { icon: "🏢", label: "Lembaga Donor" },
    { icon: "📊", label: "Think Tank" },
    { icon: "📰", label: "Media & Jurnalis" },
    { icon: "🎓", label: "Akademisi" },
  ],
  whyTitle: "Brief yang benar-benar dibaca.",
  whyPoints: [
    { title: "Bahasa yang Dapat Dipahami", desc: "Kami menerjemahkan temuan teknis ke dalam bahasa yang dapat dipahami semua kalangan." },
    { title: "Rekomendasi yang Spesifik", desc: "Bukan sekadar 'perlu ada kebijakan X', tapi 'kebijakan X harus mencakup Y dengan mekanisme Z'." },
    { title: "Desain yang Profesional", desc: "Tampilan visual yang kredibel dan sesuai standar dokumen kebijakan internasional." },
    { title: "Turnaround Cepat", desc: "Rata-rata selesai dalam 10–14 hari kerja tanpa mengorbankan kualitas." },
  ],
  faqs: [
    { q: "Apa bedanya policy brief dengan laporan riset?", a: "Policy brief adalah dokumen singkat (4–8 hal) yang fokus pada rekomendasi untuk satu isu spesifik. Laporan riset lebih panjang dan mendalam." },
    { q: "Apakah Manara menyediakan data riset sendiri?", a: "Bisa keduanya. Kami bisa mengembangkan brief berdasarkan data Anda, atau sekaligus melakukan riset dari awal." },
    { q: "Berapa lama pengerjaan satu policy brief?", a: "Rata-rata 10–14 hari kerja. Rapid brief bisa selesai dalam 5–7 hari dengan biaya tambahan." },
    { q: "Apakah brief bisa dipublikasikan atas nama organisasi kami?", a: "Ya, kami menyediakan opsi co-branding atau ghostwriting penuh sesuai kebutuhan." },
  ],
  ctaTitle: "Butuh policy brief yang benar-benar dibaca?",
  ctaDesc: "Hubungi kami dan ceritakan isu yang ingin kamu advokasikan.",
};

export const TRAINING_DATA: ServicePageData = {
  slug: "training",
  parentHref: "/layanan",
  parentLabel: "← Layanan",
  category: "Training",
  accentColor: "#5F8F8A",
  heroGrad: "radial-gradient(ellipse 80% 60% at 30% 60%, rgba(95,143,138,0.2) 0%, transparent 60%)",
  heroIcon: "△",
  heroTitle: "Kapasitas yang tumbuh",
  heroTitleAccent: "bersama organisasi.",
  heroDesc: "Program pelatihan Manara dirancang untuk meningkatkan kapasitas riset, penulisan, dan analisis kebijakan — dari individu hingga tim.",
  overviewTitle: "Pelatihan yang mengubah cara berpikir, bukan hanya cara bekerja.",
  overviewDesc: [
    "Program training Manara bukan seminar biasa. Kami merancang kurikulum berbasis kebutuhan aktual peserta, dengan metode yang menggabungkan teori, praktik, dan mentorship.",
    "Setiap program dirancang agar peserta pulang dengan kemampuan yang dapat langsung diterapkan — bukan hanya pengetahuan yang menguap setelah seminggu.",
  ],
  overviewStats: [
    { value: "Praktis", label: "Langsung bisa diterapkan" },
    { value: "Custom", label: "Kurikulum sesuai kebutuhan" },
    { value: "Mentor", label: "Pendampingan pasca pelatihan" },
    { value: "Sertifikat", label: "Dokumen resmi kelulusan" },
  ],
  features: [
    { icon: "◎", title: "Research Methodology", desc: "Metodologi riset kualitatif, kuantitatif, dan mixed methods untuk pemula hingga menengah." },
    { icon: "◇", title: "Policy Writing", desc: "Teknik penulisan policy brief, laporan kebijakan, dan dokumen advokasi yang efektif." },
    { icon: "○", title: "Data Analysis & Visualization", desc: "Pengolahan dan visualisasi data menggunakan tools yang relevan (SPSS, R, Tableau, dsb)." },
    { icon: "✦", title: "Academic Writing", desc: "Penulisan ilmiah, sitasi, dan persiapan submit ke jurnal nasional dan internasional." },
    { icon: "△", title: "Critical Thinking", desc: "Kerangka berpikir kritis untuk analisis isu publik dan pengambilan keputusan berbasis data." },
    { icon: "□", title: "Facilitation Skills", desc: "Teknik fasilitasi FGD, workshop, dan diskusi publik yang efektif." },
  ],
  processTitle: "Dari asesmen hingga sertifikasi.",
  processDesc: "Setiap program training kami dimulai dari pemahaman mendalam tentang kebutuhan peserta.",
  steps: [
    { num: "01", title: "Needs Assessment", desc: "Asesmen kebutuhan organisasi dan peserta untuk merancang kurikulum yang tepat sasaran.", duration: "3–5 hari" },
    { num: "02", title: "Curriculum Design", desc: "Perancangan silabus, modul, dan metode pembelajaran yang sesuai konteks.", duration: "1 minggu" },
    { num: "03", title: "Training Delivery", desc: "Pelaksanaan pelatihan — onsite, online, atau hybrid — dengan fasilitator berpengalaman.", duration: "1–5 hari" },
    { num: "04", title: "Practice & Assignment", desc: "Tugas praktis dan proyek kecil untuk mengkonsolidasi pembelajaran.", duration: "1–2 minggu" },
    { num: "05", title: "Evaluation & Certification", desc: "Evaluasi akhir, umpan balik, dan penerbitan sertifikat kelulusan.", duration: "2–3 hari" },
  ],
  deliverables: [
    { icon: "△", title: "Modul Pelatihan", desc: "Materi lengkap yang dapat digunakan sebagai referensi pasca pelatihan." },
    { icon: "◎", title: "Sertifikat", desc: "Sertifikat resmi dari Manara untuk setiap peserta yang menyelesaikan program." },
    { icon: "○", title: "Recording (Online)", desc: "Rekaman sesi untuk pelatihan online yang dapat diakses ulang." },
    { icon: "✦", title: "Template & Tools", desc: "Kumpulan template dan alat bantu kerja yang langsung bisa digunakan." },
    { icon: "◇", title: "Post-Training Report", desc: "Laporan evaluasi pelatihan untuk organisasi klien." },
  ],
  clients: [
    { icon: "🌱", label: "NGO & CSO" },
    { icon: "🏛️", label: "Pemerintah Daerah" },
    { icon: "🎓", label: "Mahasiswa & Alumni" },
    { icon: "📊", label: "Peneliti Muda" },
    { icon: "✍️", label: "Jurnalis & Penulis" },
    { icon: "🏢", label: "Organisasi Kampus" },
  ],
  whyTitle: "Belajar bersama mereka yang juga berpraktik.",
  whyPoints: [
    { title: "Fasilitator yang Juga Praktisi", desc: "Semua trainer Manara adalah praktisi aktif di bidangnya — bukan hanya pengajar teori." },
    { title: "Kurikulum Berbasis Konteks Lokal", desc: "Studi kasus dan contoh yang relevan dengan realitas Indonesia, khususnya Jawa Timur." },
    { title: "Small Group Learning", desc: "Rasio peserta kecil untuk memastikan setiap orang mendapat perhatian dan ruang bertanya." },
    { title: "Dukungan Pasca Pelatihan", desc: "Akses ke komunitas alumni dan sesi mentorship lanjutan setelah pelatihan selesai." },
  ],
  faqs: [
    { q: "Berapa jumlah peserta ideal per batch?", a: "Untuk pelatihan intensif, kami merekomendasikan 15–25 peserta. Untuk webinar, bisa hingga 100 peserta." },
    { q: "Apakah bisa dilaksanakan di luar kota?", a: "Ya, kami dapat melaksanakan training onsite di seluruh Indonesia dengan biaya transportasi dan akomodasi tambahan." },
    { q: "Apakah ada program khusus untuk mahasiswa?", a: "Ya, kami memiliki program tarif khusus untuk organisasi mahasiswa dan komunitas pemuda." },
    { q: "Berapa durasi program yang tersedia?", a: "Dari workshop 1 hari hingga program intensif 5 hari. Program jangka panjang (4–8 minggu) juga tersedia secara online." },
  ],
  ctaTitle: "Tingkatkan kapasitas tim dengan pelatihan yang bermakna.",
  ctaDesc: "Ceritakan kebutuhan pelatihan organisasi kamu. Kami akan merancang program yang tepat.",
};

export const CONSULTING_DATA: ServicePageData = {
  slug: "consulting",
  parentHref: "/layanan",
  parentLabel: "← Layanan",
  category: "Consulting",
  accentColor: "#8A8F5E",
  heroGrad: "radial-gradient(ellipse 80% 60% at 70% 40%, rgba(138,143,94,0.18) 0%, transparent 60%)",
  heroIcon: "✦",
  heroTitle: "Strategi yang dibangun",
  heroTitleAccent: "di atas bukti.",
  heroDesc: "Manara Consulting menyediakan layanan konsultasi kebijakan, komunikasi strategis, dan pengembangan program untuk organisasi yang ingin bergerak lebih efektif.",
  overviewTitle: "Konsultasi yang berpihak pada dampak, bukan sekadar saran.",
  overviewDesc: [
    "Manara Consulting hadir untuk organisasi yang membutuhkan perspektif eksternal yang kritis, berbasis data, dan berakar pada pemahaman mendalam tentang konteks sosial-politik Indonesia.",
    "Kami tidak menjual solusi jadi. Kami bekerja bersama klien untuk memahami masalah sesungguhnya, lalu merancang pendekatan yang paling relevan — bahkan jika itu berarti menantang asumsi awal.",
  ],
  overviewStats: [
    { value: "Kritis", label: "Perspektif yang tidak hanya mengonfirmasi" },
    { value: "Kolaboratif", label: "Bekerja bersama, bukan untuk" },
    { value: "Kontekstual", label: "Solusi yang relevan dengan realitas lokal" },
    { value: "Jangka Panjang", label: "Orientasi pada dampak, bukan output" },
  ],
  features: [
    { icon: "✦", title: "Strategic Planning", desc: "Fasilitasi penyusunan rencana strategis organisasi berbasis analisis situasi dan stakeholder." },
    { icon: "◎", title: "Policy Advocacy", desc: "Strategi advokasi kebijakan — dari pemetaan pemangku kepentingan hingga rencana komunikasi." },
    { icon: "◇", title: "Program Development", desc: "Desain program intervensi sosial berbasis teori perubahan yang terukur." },
    { icon: "○", title: "Communication Strategy", desc: "Pengembangan strategi komunikasi publik untuk lembaga dan program." },
    { icon: "△", title: "Organizational Capacity", desc: "Asesmen dan penguatan kapasitas organisasi — struktur, proses, dan SDM." },
    { icon: "□", title: "Monitoring & Evaluation", desc: "Desain sistem M&E dan evaluasi program yang sedang atau sudah berjalan." },
  ],
  processTitle: "Diagnosa sebelum resep.",
  processDesc: "Setiap engagement konsultasi dimulai dari pemahaman yang mendalam, bukan asumsi.",
  steps: [
    { num: "01", title: "Discovery & Diagnosis", desc: "Pemahaman mendalam tentang organisasi, konteks, masalah, dan tujuan melalui wawancara dan analisis dokumen.", duration: "1–2 minggu" },
    { num: "02", title: "Strategic Analysis", desc: "Analisis situasi, pemetaan stakeholder, dan identifikasi peluang serta hambatan.", duration: "1–2 minggu" },
    { num: "03", title: "Solution Design", desc: "Pengembangan rekomendasi strategis bersama tim klien melalui sesi ko-kreasi.", duration: "1–2 minggu" },
    { num: "04", title: "Implementation Support", desc: "Pendampingan implementasi rekomendasi, termasuk coaching dan problem-solving.", duration: "Ongoing" },
    { num: "05", title: "Review & Adaptation", desc: "Evaluasi berkala dan penyesuaian strategi berdasarkan perkembangan situasi.", duration: "Berkala" },
  ],
  deliverables: [
    { icon: "✦", title: "Strategic Recommendations", desc: "Dokumen rekomendasi strategis yang spesifik dan dapat ditindaklanjuti." },
    { icon: "◎", title: "Stakeholder Map", desc: "Peta pemangku kepentingan lengkap dengan analisis posisi dan pengaruh." },
    { icon: "◇", title: "Theory of Change", desc: "Kerangka teori perubahan yang memandu implementasi program." },
    { icon: "○", title: "Communication Plan", desc: "Rencana komunikasi strategis lengkap dengan pesan kunci dan saluran." },
    { icon: "△", title: "Monitoring Framework", desc: "Kerangka pemantauan dan evaluasi dengan indikator yang terukur." },
  ],
  clients: [
    { icon: "🌱", label: "NGO & CSO" },
    { icon: "🏛️", label: "Pemerintah Daerah" },
    { icon: "🏢", label: "Lembaga Donor Internasional" },
    { icon: "📊", label: "Organisasi Multilateral" },
    { icon: "🤝", label: "Yayasan & Filantropi" },
    { icon: "🎓", label: "Lembaga Riset" },
  ],
  whyTitle: "Konsultan yang juga berpikir kritis terhadap dirinya.",
  whyPoints: [
    { title: "Perspektif Independen", desc: "Kami tidak terikat pada satu ideologi atau kepentingan — memberikan analisis yang jujur meski tidak nyaman." },
    { title: "Berbasis Riset", desc: "Setiap rekomendasi didukung oleh data dan analisis yang dapat diverifikasi." },
    { title: "Ko-kreasi, Bukan Dikte", desc: "Kami bekerja bersama tim klien, bukan memberikan solusi dari menara gading." },
    { title: "Transfer Kapasitas", desc: "Kami memastikan klien bisa melanjutkan tanpa kami — bukan menciptakan ketergantungan." },
  ],
  faqs: [
    { q: "Apa yang membedakan Manara dari konsultan lain?", a: "Kami berangkat dari perspektif intelektual yang kritis, bukan sekadar framework standar. Kami juga lebih fokus pada transfer kapasitas daripada dependensi." },
    { q: "Berapa lama biasanya satu engagement konsultasi?", a: "Sangat bervariasi — dari 1 bulan untuk proyek spesifik hingga 12 bulan untuk pendampingan strategis." },
    { q: "Apakah Manara bisa dilibatkan sebagai advisor independen?", a: "Ya, kami menerima peran sebagai advisory board member, advisor strategis, atau reviewer independen." },
    { q: "Bagaimana struktur biaya konsultasi?", a: "Kami menawarkan beberapa model: project-based, retainer bulanan, atau per hari konsultasi. Diskusikan kebutuhan kamu dengan kami." },
  ],
  ctaTitle: "Butuh perspektif eksternal yang jujur dan berbasis data?",
  ctaDesc: "Kami tidak hanya menjawab pertanyaan yang kamu ajukan — kami juga membantu kamu mengajukan pertanyaan yang tepat.",
};

export const EVENT_DATA: ServicePageData = {
  slug: "event",
  parentHref: "/layanan",
  parentLabel: "← Layanan",
  category: "Event",
  accentColor: "#C6AD8A",
  heroGrad: "radial-gradient(ellipse 80% 60% at 50% 80%, rgba(198,173,138,0.18) 0%, transparent 60%)",
  heroIcon: "□",
  heroTitle: "Ruang diskusi yang",
  heroTitleAccent: "menggerakkan gagasan.",
  heroDesc: "Manara merancang dan mengelola forum, seminar, diskusi publik, dan program kolaborasi yang membawa gagasan ke ruang nyata — bermakna bagi peserta dan berdampak bagi publik.",
  overviewTitle: "Event bukan sekadar pertemuan. Ini ruang untuk mengubah cara berpikir.",
  overviewDesc: [
    "Program event Manara dirancang dengan filosofi yang sama dengan seluruh kerja kami: kedalaman, relevansi, dan dampak. Setiap forum yang kami kelola bukan sekadar wadah berkumpul.",
    "Kami merancang pengalaman yang memicu dialog bermakna, mempertemukan perspektif yang berbeda, dan menghasilkan pemikiran baru yang dapat dibawa pulang setiap peserta.",
  ],
  overviewStats: [
    { value: "Bermakna", label: "Dialog yang menghasilkan gagasan baru" },
    { value: "Inklusif", label: "Terbuka untuk berbagai latar belakang" },
    { value: "Terdokumentasi", label: "Setiap diskusi diabadikan dan dipublikasikan" },
    { value: "Berdampak", label: "Output yang dapat ditindaklanjuti" },
  ],
  features: [
    { icon: "□", title: "Public Forum", desc: "Forum diskusi publik terbuka dengan narasumber dari berbagai sektor dan latar belakang." },
    { icon: "◎", title: "Policy Dialogue", desc: "Dialog kebijakan tertutup antara pembuat kebijakan, peneliti, dan praktisi." },
    { icon: "○", title: "Workshop & Training", desc: "Sesi pembelajaran intensif dengan output konkret dan modul yang dibawa pulang." },
    { icon: "✦", title: "Symposium & Seminar", desc: "Pertemuan akademik dan praktisi untuk berbagi temuan riset dan pengalaman lapangan." },
    { icon: "◇", title: "Community Dialogue", desc: "Dialog berbasis komunitas yang membawa suara akar rumput ke meja kebijakan." },
    { icon: "△", title: "Youth Summit", desc: "Forum khusus anak muda untuk mendiskusikan isu-isu yang paling relevan bagi generasi mereka." },
  ],
  processTitle: "Dari konsep hingga dokumentasi.",
  processDesc: "Setiap event Manara dikelola dengan standar yang sama ketatnya dengan proyek riset kami.",
  steps: [
    { num: "01", title: "Concept Development", desc: "Pengembangan konsep, tema, dan tujuan event bersama klien atau tim internal.", duration: "1–2 minggu" },
    { num: "02", title: "Speaker & Content Curation", desc: "Kurasi narasumber, materi, dan agenda yang relevan dengan tujuan forum.", duration: "2–3 minggu" },
    { num: "03", title: "Logistics & Promotion", desc: "Pengelolaan teknis, venue, pendaftaran peserta, dan promosi event.", duration: "2–4 minggu" },
    { num: "04", title: "Event Execution", desc: "Fasilitasi dan pengelolaan event oleh tim Manara yang berpengalaman.", duration: "1–3 hari" },
    { num: "05", title: "Documentation & Follow-up", desc: "Dokumentasi, laporan event, dan publikasi temuan utama untuk publik.", duration: "1–2 minggu" },
  ],
  deliverables: [
    { icon: "□", title: "Event Report", desc: "Laporan lengkap jalannya event termasuk notulensi dan key takeaways." },
    { icon: "◎", title: "Dokumentasi Foto/Video", desc: "Dokumentasi visual berkualitas untuk arsip dan publikasi." },
    { icon: "○", title: "Summary Publikasi", desc: "Ringkasan diskusi yang dipublikasikan di platform Manara." },
    { icon: "✦", title: "Policy Recommendations", desc: "Rekomendasi kebijakan hasil diskusi (untuk policy dialogue)." },
    { icon: "△", title: "Post-Event Survey", desc: "Survei kepuasan dan evaluasi dampak kepada peserta." },
  ],
  clients: [
    { icon: "🏛️", label: "Pemerintah & Dinas" },
    { icon: "🌱", label: "NGO & Komunitas" },
    { icon: "🎓", label: "Universitas & Kampus" },
    { icon: "🏢", label: "Korporasi & Yayasan" },
    { icon: "📊", label: "Lembaga Penelitian" },
    { icon: "🤝", label: "Organisasi Pemuda" },
  ],
  whyTitle: "Forum yang meninggalkan bekas, bukan sekadar absensi.",
  whyPoints: [
    { title: "Kurasi Narasumber yang Ketat", desc: "Kami tidak mengundang pembicara karena jabatan, tapi karena kontribusi substantif yang bisa mereka berikan." },
    { title: "Fasilitasi yang Aktif", desc: "Tim kami memastikan setiap diskusi berjalan substantif, inklusif, dan menghasilkan output yang konkret." },
    { title: "Dokumentasi yang Berguna", desc: "Setiap event kami dokumentasikan dengan baik untuk memastikan gagasan yang lahir bisa diakses publik." },
    { title: "Jaringan yang Bermakna", desc: "Peserta tidak hanya bertemu, tapi juga terhubung dalam ekosistem intelektual Manara yang lebih luas." },
  ],
  faqs: [
    { q: "Apakah Manara bisa mengelola event di luar kota?", a: "Ya, kami telah mengelola event di berbagai kota. Biaya transportasi dan akomodasi akan disesuaikan." },
    { q: "Berapa peserta minimum untuk satu event?", a: "Untuk workshop intensif, minimal 15 peserta. Untuk forum publik, tidak ada batas minimum." },
    { q: "Apakah Manara menyediakan venue?", a: "Kami dapat membantu pencarian venue, namun biaya sewa venue di luar paket layanan kami." },
    { q: "Bagaimana dengan event hybrid (online + offline)?", a: "Ya, kami memiliki kapabilitas untuk mengelola event hybrid dengan platform digital yang sesuai." },
  ],
  ctaTitle: "Wujudkan forum yang benar-benar berdampak.",
  ctaDesc: "Ceritakan ide event kamu. Kami bantu dari konsep hingga dokumentasi.",
};

export const MEDIA_SERVICE_DATA: ServicePageData = {
  slug: "media",
  parentHref: "/layanan",
  parentLabel: "← Layanan",
  category: "Media",
  accentColor: "#266c87",
  heroGrad: "radial-gradient(ellipse 80% 60% at 30% 30%, rgba(38,108,135,0.2) 0%, transparent 60%)",
  heroIcon: "◉",
  heroTitle: "Gagasan yang menjangkau",
  heroTitleAccent: "lebih banyak orang.",
  heroDesc: "Ekosistem media Manara menggabungkan kekuatan tulisan, audio, dan visual untuk menyebarkan gagasan ke publik yang lebih luas — dengan kedalaman yang tidak dikorbankan.",
  overviewTitle: "Media sebagai alat, bukan tujuan.",
  overviewDesc: [
    "Manara percaya bahwa medium yang tepat dapat melipatgandakan dampak sebuah gagasan. Karena itu kami mengembangkan ekosistem media yang beragam — dari jurnal akademik hingga konten sosial media.",
    "Semua kanal media Manara terhubung dalam satu filosofi yang sama: kedalaman, kejujuran, dan relevansi. Format boleh berbeda, standar tidak pernah dikompromikan.",
  ],
  overviewStats: [
    { value: "3+", label: "Kanal media aktif" },
    { value: "Mingguan", label: "Frekuensi newsletter" },
    { value: "Publik", label: "Semua konten akses terbuka" },
    { value: "Organik", label: "Pertumbuhan tanpa iklan berbayar" },
  ],
  features: [
    { icon: "✦", title: "Manara Journal", desc: "Artikel panjang dan analisis mendalam di website — esai, opini, dan investigasi." },
    { icon: "◇", title: "Manara Paper", desc: "Publikasi riset formal — policy paper, working paper, dan policy brief." },
    { icon: "○", title: "Surat Manara", desc: "Newsletter mingguan berisi kurasi gagasan, analisis, dan bacaan pilihan." },
    { icon: "▷", title: "Suara Manara", desc: "Serial video pendek di Instagram — gagasan besar dalam format yang tajam." },
    { icon: "◉", title: "Manara Podcast", desc: "Percakapan mendalam dengan pemikir dan praktisi di YouTube." },
  ],
  processTitle: "Dari gagasan ke distribusi.",
  processDesc: "Setiap konten Manara melalui proses editorial yang ketat sebelum sampai ke publik.",
  steps: [
    { num: "01", title: "Ideation & Pitching", desc: "Pengajuan ide konten oleh tim atau kontributor, evaluasi relevansi dan kedalaman.", duration: "Ongoing" },
    { num: "02", title: "Research & Writing", desc: "Riset mendalam dan penulisan konten sesuai standar editorial Manara.", duration: "1–2 minggu" },
    { num: "03", title: "Editorial Review", desc: "Review oleh editor untuk akurasi fakta, kedalaman argumen, dan kualitas bahasa.", duration: "3–5 hari" },
    { num: "04", title: "Production", desc: "Desain visual, rekaman, atau pengolahan media sesuai format kanal.", duration: "2–5 hari" },
    { num: "05", title: "Publishing & Distribution", desc: "Publikasi di kanal yang sesuai dan distribusi ke subscriber serta jaringan.", duration: "1 hari" },
  ],
  deliverables: [
    { icon: "✦", title: "Artikel Jurnal", desc: "Publikasi di /publikasi/artikel dengan SEO dan metadata lengkap." },
    { icon: "◇", title: "Paper & Brief", desc: "Dokumen PDF yang dapat diunduh dan dibagikan." },
    { icon: "○", title: "Newsletter", desc: "Email ke seluruh subscriber dengan konten eksklusif." },
    { icon: "▷", title: "Video Konten", desc: "Konten video di Instagram dan YouTube." },
    { icon: "◉", title: "Episode Podcast", desc: "Audio dan video podcast di platform streaming." },
  ],
  clients: [
    { icon: "📖", label: "Pembaca Umum" },
    { icon: "🎓", label: "Akademisi & Mahasiswa" },
    { icon: "🏛️", label: "Praktisi Kebijakan" },
    { icon: "✍️", label: "Jurnalis & Penulis" },
    { icon: "🌱", label: "Aktivis & Advokat" },
    { icon: "💡", label: "Pemikir Muda" },
  ],
  whyTitle: "Konten yang diingat, bukan sekadar dikonsumsi.",
  whyPoints: [
    { title: "Standar Editorial yang Ketat", desc: "Setiap konten melalui review editorial sebelum dipublikasikan — tidak ada konten yang lolos tanpa verifikasi." },
    { title: "Multi-format, Satu Kualitas", desc: "Dari artikel panjang hingga video pendek, standar kedalaman dan kejujuran tidak berubah." },
    { title: "Open Access", desc: "Semua konten Manara dapat diakses gratis — karena pengetahuan adalah hak, bukan privilege." },
    { title: "Komunitas yang Aktif", desc: "Setiap konten membangun komunitas pembaca yang kritis dan engaged." },
  ],
  faqs: [
    { q: "Bagaimana cara berkontribusi ke Manara?", a: "Kirimkan pitch artikel atau paper melalui form di halaman Manapeople atau email ke manararesearch@gmail.com." },
    { q: "Apakah ada kompensasi untuk kontributor?", a: "Saat ini Manara beroperasi berbasis sukarela. Ke depan, program honorarium kontributor sedang dalam perencanaan." },
    { q: "Apakah Manara menerima iklan atau sponsorship?", a: "Tidak. Manara berkomitmen untuk tetap independen dari kepentingan komersial. Kami didukung oleh donasi dan kerja sama program." },
    { q: "Bagaimana cara berlangganan newsletter?", a: "Langsung isi form di halaman /insight/newsletter atau di footer website kami. Gratis selamanya." },
  ],
  ctaTitle: "Ingin gagasanmu menjangkau lebih banyak orang?",
  ctaDesc: "Bergabunglah sebagai kontributor atau mitra konten Manara.",
};